# Generated by Django 3.1.6 on 2021-02-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
